sonar.projectName=transcribe-api
sonar.projectKey=transcribe-api
sonar.language=py
sonar.python.version=3.13
sonar.sources=src/transcribe_api
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
