apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the HMCTS Transcribe backend
name: transcribe-api
home: https://github.com/hmcts/transcribe-api
version: 0.0.1
maintainers:
  - name: HMCTS Transcribe team
dependencies:
  - name: python
    version: 0.1.1
    repository: "oci://hmctsprod.azurecr.io/helm"
  - name: postgresql
    version: 1.1.1
    repository: "oci://hmctsprod.azurecr.io/helm"
    condition: postgresql.enabled
