"""empty message

Revision ID: d3ee506fc6d8
Revises: de7d26bcb326
Create Date: 2025-07-30 18:30:17.040029

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "d3ee506fc6d8"
down_revision = "de7d26bcb326"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("azure_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f("ix_user_azure_user_id"), "user", ["azure_user_id"], unique=True)
    op.drop_column("user", "hide_citations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hide_citations", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_user_azure_user_id"), table_name="user")
    op.drop_column("user", "azure_user_id")
    # ### end Alembic commands ###
