"""empty message

Revision ID: de7d26bcb326
Revises:
Create Date: 2025-07-30 17:03:16.578563

"""

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "de7d26bcb326"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime", sa.DateTime(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hide_citations", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_table(
        "transcription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "minuteversion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime", sa.DateTime(), nullable=True),
        sa.Column("html_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("transcription_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("star_rating", sa.Integer(), nullable=True),
        sa.Column("star_rating_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_generating", sa.Boolean(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["transcription_id"], ["transcription.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transcriptionjob",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime", sa.DateTime(), nullable=True),
        sa.Column("transcription_id", sa.Uuid(), nullable=False),
        sa.Column("dialogue_entries", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("s3_audio_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["transcription_id"], ["transcription.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcriptionjob")
    op.drop_table("minuteversion")
    op.drop_table("transcription")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
