"""Add has_completed_onboarding to users

Revision ID: ed7aa9a4e0f2
Revises: d3ee506fc6d8
Create Date: 2025-09-16 12:19:52.644350

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed7aa9a4e0f2"
down_revision = "d3ee506fc6d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column("user", sa.Column("has_completed_onboarding", sa.Boolean(), nullable=True))
    # Set default value for existing users (assuming they haven't completed onboarding)
    op.execute('UPDATE "user" SET has_completed_onboarding = false WHERE has_completed_onboarding IS NULL')
    # Now make it NOT NULL
    op.alter_column("user", "has_completed_onboarding", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_completed_onboarding")
    # ### end Alembic commands ###
